version: "3.7"

services:
  app:
    hostname: "librate-app"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 6
        window: 60s
    build:
      context: .
      cache_from:
        - "golang:1.21-alpine"
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
      - "3030:3030"
    networks:
      - librate-net
    healthcheck:
      test:
        ["CMD", "curl", "-f", "-X", "GET", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 4s
      retries: 3
  db:
    hostname: "librate-db"
    networks:
      - librate-net
    restart: always
    build:
      context: ./src/db
    ports:
      - "5432:5432"
    shm_size: 256mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    hostname: "librate-redis"
    restart: always
    networks:
      - librate-net
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  librate-net:
    name: librate-net
    external: true
