version: "3.7"

services:
  app:
    hostname: "librate-app"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 6
        window: 60s
    build:
      context: .
      cache_from:
        - "golang:1.21-alpine"
    depends_on:
      - db
      - redis
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3030:3030"
    networks:
      - librate-net
    healthcheck:
      test:
        ["CMD", "curl", "-f", "-X", "GET", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 4s
      retries: 3
  db:
    hostname: "librate-db"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - librate-net
    restart: always
    build:
      context: ./db
    ports:
      - "5432:5432"
    shm_size: 4gb
    depends_on:
      - couchdb
    links:
        - couchdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  couchdb:
     # WARN: DO NOT CHANGE THE HOSTNAME. Postgres sync trigger depends on it
    hostname: "librate-search"
    restart: always
    networks:
      - librate-net
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb/config.ini:/opt/couchdb/etc/local.ini
    image: couchdb:3.3
    ports:
      - "5984:5984"
  redis:
    hostname: "librate-redis"
    restart: always
    networks:
      - librate-net
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  prometheus:
    hostname: "librate-prometheus"
    restart: always
    networks:
      - librate-net
    image: prom/prometheus:main
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "GET", "http://localhost:9090/-/healthy"]
      interval: 5s
      timeout: 5s
      retries: 5
    entrypoint: ["echo", "Manual start enabled"]
  grafana:
    hostname: "librate-grafana"
    restart: always
    networks:
      - librate-net
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    links:
        - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=CHANGE_ME
      - GF_SECURITY_ADMIN_USER=librate
      - GF_USERS_ALLOW_SIGN_UP=false
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "GET", "http://localhost:3000/"]
      interval: 5s
      timeout: 5s
      retries: 5
    entrypoint: ["echo", "Manual start enabled"]
networks:
  librate-net:
    name: librate-net
    external: true
