version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LIBRATE_ENV="dev"
      - HOME="/app"
      - PATH="/app/bin:$PATH"
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    networks:
      - app-network
    dns:
      - 9.9.9.9
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "GET", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 4s
      retries: 3
  db:
    restart: always
    build:
      context: db
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - 5432:5432
    shm_size: 256mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - 'POSTGRES_DB=librate'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - app-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  app-network:
    internal: true
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
volumes:
  pg-data:
  redis-data:
