version: "3.8"

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LIBRATE_ENV="dev"
      - HOME="/app"
      - GIT_TAG="0.6.1"
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "GET", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 4s
      retries: 3
  db:
    hostname: "librate-db"
    networks:
      - librate-net
    restart: always
    build:
      context: ./db
    ports:
      - "5432:5432"
    shm_size: 256mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - ./db/.env
  redis:
    restart: always
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
