version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - LIBRATE_ENV="dev"
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    networks:
      - app-network
  db:
    build:
      context: db
      dockerfile: Dockerfile
    networks:
      - app-network
  redis:
    image: redis:7-alpine
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
