version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - LIBRATE_ENV="dev"
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    networks:
      - app-network
      - external-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "GET", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 4s
      retries: 3
  db:
    restart: always
    build:
      context: db
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - 5432:5432
    shm_size: 256mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  external-network:
    external: true
  app-network:
    internal: true
