fiber:
  host: "localhost"
  port: 3000
  prefork: true
  reduceMemUsage: false
  staticDir: "./static"
  # in seconds
  powInterval: 300
  powDifficulty: 30000
secret: "librate-secret-key"
database:
    engine: "postgres"
    pgConfig: "/usr/bin/pg_config"
    host: "localhost"
    port: 5432
    database: "librate"
    testDatabase: "librate_test"
    user: "postgres"
    password: "postgres"
    startCmd: "sudo systemctl start postgresql"
redis:
  host: "localhost"
  port: 6379
  username: ""
  password: ""
  database: 0
logging:
  level: "info"
  output: "stdout"
  format: "json"
# dev or production
librateEnv: "production"
