fiber:
  host: "localhost"
  port: 3000
  prefork: true
  reduceMemUsage: false
  staticDir: "./static"
  # in seconds
  powInterval: 300
  powDifficulty: 30000
secret: "librate-secret-key"
database:
    engine: "postgres"
    pgConfig: "/usr/bin/pg_config"
    host: "localhost"
    port: 5432
    database: "librate"
    user: "postgres"
    password: "postgres"
    startCmd: "sudo systemctl start postgresql"
    autoMigrate: true
    exitAfterMigration: false
redis:
  host: "localhost"
  port: 6379
  username: ""
  password: ""
  database: 0
logging:
  level: "info"
  output: "stdout"
  format: "console"
  caller: true
  timestamp:
    enabled: true
    format: "2006-01-0215:04:05.000Z07:00" 
# dev or production
librateEnv: "production"
# relative paths supported
keys:
  public: "~/.ssh/id_rsa.pub"
  private: "~/.ssh/private_key"
