fiber:
  host: "localhost"
  port: 3000
  prefork: true
  reduceMemUsage: false
  staticDir: "./static"
secret: "librate-secret-key"
database:
  - engine: "postgres"
    pgConfig: "/usr/bin/pg_config"
    host: "localhost"
    port: 5432
    database: "librate"
    testDatabase: "librate_test"
    user: "postgres"
    password: "postgres"
    startCmd: "sudo systemctl start postgresql"
logging:
  level: "info"
  output: "stdout"
  format: "json"
# dev or production
librateEnv: "production"
