# YOU MUST encrypt the config file using AGE/SOPS, see the relevant section in the README
fiber:
  host: "localhost"
  domain: "lr.localhost"
  port: 3000
  prefork: true
  reduceMemUsage: false
  staticDir: "./static"
  # in seconds
  powInterval: 300
  powDifficulty: 30000
  tls: false
  # -1 for graceful shutdown that will wait indefintely
  shutdownTimeout: 10
  maxUploadSize: 4194304 # 4MB
  thumbnailing:
    namespaces:
      - names:  
          - "film_cover"
          - "album_poster"
          - "profile"
        size: 
          width: 500
          height: 500
# used to encrypt sensitive data that is stored in session redis store
secret: "librate-secret-key"
database:
  engine: "postgres"
  pgConfig: "/usr/bin/pg_config"
  host: "localhost"
  port: 5432
  database: "librate"
  user: "postgres"
  password: "postgres"
  autoMigrate: true
  exitAfterMigration: false
  retryAttempts: 30
redis:
  host: "localhost"
  port: 6379
  username: ""
  password: ""
  # database for use by the cache middleware and so on
  cacheDb: 0
  csrfDb: 2
  powDb: 3
logging:
  level: "info"
  output: "stdout"
  format: "console"
  caller: true
  timestamp:
    enabled: true
    format: "2006-01-0215:04:05.000Z07:00"
grpc:
  host: "127.0.0.1"
  port: 3030
  shutdownTimeout: 10
# development or production
librateEnv: "production"
jwtSecret: "librate-jwt-secret"
external:
  import_sources:
    - "spotify"
    - "id3"
    - "json"
  spotify_client_id: "spotify-client-id"
  spotify_client_secret: "spotify-client-secret"
