global:
  scrape_interval: 60s
  evaluation_interval: 120s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['librate-app:3000']
  - job_name: 'db'
    static_configs:
      - targets: ['librate-db:5432']
  - job_name: 'redis'
    static_configs:
      - targets: ['librate-redis:6379']
