// Code generated by "stringer -type=LangID"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[English-0]
	_ = x[Spanish-1]
	_ = x[French-2]
	_ = x[German-3]
	_ = x[Chinese-4]
	_ = x[Japanese-5]
	_ = x[Korean-6]
	_ = x[Arabic-7]
	_ = x[Hebrew-8]
	_ = x[Hindi-9]
	_ = x[Polish-10]
	_ = x[Russian-11]
	_ = x[Czech-12]
	_ = x[Dutch-13]
	_ = x[Greek-14]
	_ = x[Italian-15]
	_ = x[Swedish-16]
	_ = x[Turkish-17]
	_ = x[Norwegian-18]
	_ = x[Portuguese-19]
	_ = x[Finnish-20]
	_ = x[Thai-21]
	_ = x[Indonesian-22]
	_ = x[Vietnamese-23]
	_ = x[Farsi-24]
	_ = x[Tagalog-25]
	_ = x[Swahili-26]
	_ = x[Serbian-27]
	_ = x[Croatian-28]
	_ = x[Bosnian-29]
	_ = x[Slovenian-30]
	_ = x[Slovak-31]
	_ = x[Macedonian-32]
	_ = x[Albanian-33]
	_ = x[Bulgarian-34]
	_ = x[Romanian-35]
	_ = x[Hungarian-36]
	_ = x[Latvian-37]
	_ = x[Lithuanian-38]
	_ = x[Estonian-39]
	_ = x[Ukrainian-40]
	_ = x[Belarusian-41]
	_ = x[Malay-42]
	_ = x[Malayalam-43]
	_ = x[Tamil-44]
	_ = x[Telugu-45]
	_ = x[Kannada-46]
	_ = x[Marathi-47]
	_ = x[Gujarati-48]
	_ = x[Bengali-49]
	_ = x[Punjabi-50]
	_ = x[Urdu-51]
	_ = x[Mongolian-52]
	_ = x[Amharic-53]
	_ = x[Icelandic-54]
	_ = x[Maltese-55]
	_ = x[Unknown-56]
	_ = x[Others-57]
}

const _LangID_name = "EnglishSpanishFrenchGermanChineseJapaneseKoreanArabicHebrewHindiPolishRussianCzechDutchGreekItalianSwedishTurkishNorwegianPortugueseFinnishThaiIndonesianVietnameseFarsiTagalogSwahiliSerbianCroatianBosnianSlovenianSlovakMacedonianAlbanianBulgarianRomanianHungarianLatvianLithuanianEstonianUkrainianBelarusianMalayMalayalamTamilTeluguKannadaMarathiGujaratiBengaliPunjabiUrduMongolianAmharicIcelandicMalteseUnknownOthers"

var _LangID_index = [...]uint16{0, 7, 14, 20, 26, 33, 41, 47, 53, 59, 64, 70, 77, 82, 87, 92, 99, 106, 113, 122, 132, 139, 143, 153, 163, 168, 175, 182, 189, 197, 204, 213, 219, 229, 237, 246, 254, 263, 270, 280, 288, 297, 307, 312, 321, 326, 332, 339, 346, 354, 361, 368, 372, 381, 388, 397, 404, 411, 417}

func (i LangID) String() string {
	if i < 0 || i >= LangID(len(_LangID_index)-1) {
		return "LangID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LangID_name[_LangID_index[i]:_LangID_index[i+1]]
}
